### ISSUE TITLE
[Seeking clarification] The training data is not shuffled, while test data is. Is it on purpose?

### ISSUE THREAD

**Issue by JosephKJ** [xuyxu/Deep-Clustering-Network#2]
Hi @xuyxu

Thank you for your nice repo. I am wondering whether the training data is not shuffled, while test data is, on purpose?

Thanks!

**Comment by xuyxu** [comment]
I am sorry @JosephKJ, I cannot remember the reason on using `shuffle=False` for training data and `shuffle=True` for evaluatoin data ;-(

Maybe you could try out shuffling the training data, and see if there is any difference.

**Comment by JosephKJ** [comment]
Thanks for the reply, there’s a sharp drop in accuracy when we invert the
shuffling.

**Comment by xuyxu** [comment]
Thanks!
